name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type
        required: true
        default: release
        type: choice
        options: [debug, release]

env:
  JAVA_VERSION: '17'
  ANDROID_COMPILE_SDK: '34'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ env.JAVA_VERSION }}

    # ---------- 安装 SDK ----------
    - uses: android-actions/setup-android@v3   # 官方 Action :contentReference[oaicite:2]{index=2}
      with:
        packages: |
          platform-tools
          platforms;android-${{ env.ANDROID_COMPILE_SDK }}
          build-tools;34.0.0

    # ---------- 缓存 ----------
    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
        restore-keys: gradle-${{ runner.os }}-

    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-${{ runner.os }}-

    - run: npm ci --prefer-offline --no-audit

    # ---------- 解码 JKS 并写 key.properties ----------
    - name: Prepare signing
      run: |
        echo "$ANDROID_SIGNING_KEY_BASE64" | base64 -d > android/app/tsinghar-release.jks
        cat <<EOF > android/key.properties
        storePassword=$ANDROID_KEYSTORE_PASSWORD
        keyPassword=$ANDROID_KEY_PASSWORD
        keyAlias=$ANDROID_KEY_ALIAS
        storeFile=tsinghar-release.jks
        EOF
      env:
        ANDROID_SIGNING_KEY_BASE64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
        ANDROID_KEYSTORE_PASSWORD:  ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_PASSWORD:       ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEY_ALIAS:          ${{ secrets.ANDROID_KEY_ALIAS }}

    # ---------- 构建 ----------
    - name: Assemble
      run: |
        cd android
        if [[ "${{ github.event.inputs.build_type }}" == "debug" ]]; then
          ./gradlew assembleDebug --no-daemon --stacktrace
        else
          ./gradlew assembleRelease --no-daemon --stacktrace
        fi

    # ---------- 签名验证 ----------
    - name: Verify signing
      if: github.event.inputs.build_type == 'release'
      run: apksigner verify -v android/app/build/outputs/apk/release/*.apk

    # ---------- 上传 ----------
    - uses: actions/upload-artifact@v4
      with:
        name: android-${{ github.event.inputs.build_type }}-apks
        path: android/app/build/outputs/apk/${{ github.event.inputs.build_type }}/*.apk
        retention-days: 30
