name: Build Capacitor Android (debug / release)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 请选择构建类型
        required: true
        default: debug
        type: choice
        options: [debug, release]

env:
  SDK_VERSION: "34"
  JAVA_VERSION: "21"           # Capacitor 7 必须 Java 21
  NODE_VERSION: "20"

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    steps:
    # ① 拉代码
    - uses: actions/checkout@v4

    # ② Java 21
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: gradle

    # ③ Node
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    # ④ Android SDK（单行空格分隔）
    - uses: android-actions/setup-android@v3
      with:
        packages: "platform-tools platforms;android-${{ env.SDK_VERSION }} build-tools;34.0.0"
        accept-android-sdk-licenses: true

    # ⑤ 安装依赖 + 构建前端
    - run: npm ci --prefer-offline
    - run: npm run build           # Angular/Vue/React 均保持此脚本

    # ⑥ Capacitor 同步
    - run: |
        npm i -g @capacitor/cli
        npx cap sync android

    # ⑦ 写入 keystore & keystore.properties
    - name: Prepare signing
      if: ${{ inputs.build_type == 'release' }}
      env:
        ANDROID_SIGNING_KEY_BASE64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
        ANDROID_KEYSTORE_PASSWORD:  ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_PASSWORD:       ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEY_ALIAS:          ${{ secrets.ANDROID_KEY_ALIAS }}
      run: |
        echo "$ANDROID_SIGNING_KEY_BASE64" | base64 -d > android/app/tsinghar-release.jks
        cat > android/keystore.properties <<EOF
        storePassword=$ANDROID_KEYSTORE_PASSWORD
        keyPassword=$ANDROID_KEY_PASSWORD
        keyAlias=$ANDROID_KEY_ALIAS
        storeFile=tsinghar-release.jks
        EOF

    # ⑧ 编译
    - name: Gradle assemble
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assemble${{ inputs.build_type == 'release' && 'Release' || 'Debug' }} \
                 -Pandroid.injected.signing.store.file=app/tsinghar-release.jks \
                 -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
                 -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
                 -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }} \
                 --no-daemon --stacktrace

    # ⑨ ZIPALIGN + 二次签名 (保险开 V1/V2)
    - name: Zipalign & apksigner
      if: ${{ inputs.build_type == 'release' }}
      run: |
        APK_IN=$(ls android/app/build/outputs/apk/release/*.apk | head -n1)
        zipalign -v 4 "$APK_IN" aligned.apk
        apksigner sign --ks android/app/tsinghar-release.jks \
                       --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
                       --ks-pass pass:${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
                       --key-pass pass:${{ secrets.ANDROID_KEY_PASSWORD }} \
                       --out signed.apk \
                       --v1-signing-enabled true \
                       --v2-signing-enabled true \
                       --v3-signing-enabled true \
                       aligned.apk
        mv signed.apk "$APK_IN"

    # ⑩ 验签
    - run: apksigner verify -v android/app/build/outputs/apk/${{ inputs.build_type }}/*.apk

    # ⑪ 上传产物
    - uses: actions/upload-artifact@v4
      with:
        name: capacitor-android-${{ inputs.build_type }}-apk
        path: android/app/build/outputs/apk/${{ inputs.build_type }}/*.apk
        retention-days: 14
