name: Build Capacitor Android APK (release)

on:
  push:
    branches: [main]    # 合并到 main 即出一个正式包
  workflow_dispatch:    # 也允许手动触发

env:
  SDK_VERSION: "34"
  JAVA_VERSION: "21"
  NODE_VERSION: "20"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: gradle

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - uses: android-actions/setup-android@v3
      with:
        packages: "platform-tools platforms;android-${{ env.SDK_VERSION }} build-tools;34.0.0"
        accept-android-sdk-licenses: true

    - run: npm ci --prefer-offline
    - run: npm run build
    - run: |
        npm i -g @capacitor/cli
        npx cap sync android

    # 解码 keystore
    - env:
        ANDROID_SIGNING_KEY_BASE64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
        ANDROID_KEYSTORE_PASSWORD:  ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_PASSWORD:       ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEY_ALIAS:          ${{ secrets.ANDROID_KEY_ALIAS }}
      run: |
        echo "$ANDROID_SIGNING_KEY_BASE64" | base64 -d > android/app/release.jks
        cat > android/keystore.properties <<EOF
        storePassword=$ANDROID_KEYSTORE_PASSWORD
        keyPassword=$ANDROID_KEY_PASSWORD
        keyAlias=$ANDROID_KEY_ALIAS
        storeFile=release.jks
        EOF

    # assembleRelease
    - run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease \
                 -Pandroid.injected.signing.store.file=app/release.jks \
                 -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
                 -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
                 -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }} \
                 --no-daemon --stacktrace

    # zipalign + apksigner 双签
    - run: |
        APK_IN=$(ls android/app/build/outputs/apk/release/*.apk | head -n1)
        zipalign -v 4 "$APK_IN" aligned.apk
        apksigner sign --ks android/app/release.jks \
                       --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
                       --ks-pass pass:${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
                       --key-pass pass:${{ secrets.ANDROID_KEY_PASSWORD }} \
                       --out signed.apk \
                       --v1-signing-enabled true \
                       --v2-signing-enabled true \
                       --v3-signing-enabled true \
                       aligned.apk
        mv signed.apk "$APK_IN"
        apksigner verify -v "$APK_IN"

    - uses: actions/upload-artifact@v4
      with:
        name: capacitor-android-release-apk
        path: android/app/build/outputs/apk/release/*.apk
        retention-days: 30
