name: Build (debug or release)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: debug / release
        required: true
        default: debug
        type: choice
        options: [debug, release]

env:
  SDK_VERSION: '34'
  JAVA_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
    - uses: android-actions/setup-android@v3
      with:
        packages: |
          platform-tools
          platforms;android-${{ env.SDK_VERSION }}
          build-tools;34.0.0

    - run: npm ci --prefer-offline --no-audit

    # debug 构建无需签名步骤
    - name: Assemble
      run: |
        cd android
        if [[ "${{ github.event.inputs.build_type }}" == "debug" ]]; then
          ./gradlew assembleDebug  --no-daemon
        else
          echo "$ANDROID_SIGNING_KEY_BASE64" | base64 -d > app/tsinghar-release.jks
          echo -e "storePassword=$ANDROID_KEYSTORE_PASSWORD\nkeyPassword=$ANDROID_KEY_PASSWORD\nkeyAlias=$ANDROID_KEY_ALIAS\nstoreFile=tsinghar-release.jks" > ../key.properties
          ./gradlew assembleRelease --no-daemon
        fi
      env:
        ANDROID_SIGNING_KEY_BASE64:  ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
        ANDROID_KEYSTORE_PASSWORD:   ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_PASSWORD:        ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEY_ALIAS:           ${{ secrets.ANDROID_KEY_ALIAS }}

    - uses: actions/upload-artifact@v4
      with:
        name: android-${{ github.event.inputs.build_type }}-apks
        path: android/app/build/outputs/apk/${{ github.event.inputs.build_type }}/*.apk
        retention-days: 14
