name: Build Android APK (release)

on:
  workflow_dispatch: {}   # 手动点一下就触发

env:
  SDK_VERSION: "34"
  JAVA_VERSION: "17"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platform-tools platforms;android-${{ env.SDK_VERSION }} build-tools;34.0.0"
          accept-android-sdk-licenses: "true"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - run: npm ci --prefer-offline --no-audit

      # keystore
      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}" | base64 -d > android/app/tsinghar-release.jks
          cat > android/keystore.properties <<EOF
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=tsinghar-release.jks
          EOF

      - name: assembleRelease
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Verify signing
        run: apksigner verify -v android/app/build/outputs/apk/release/*.apk

      - uses: actions/upload-artifact@v4
        with:
          name: android-release-apks
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 30
