name: Build Android APK
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type
        required: true
        default: release
        type: choice
        options: [debug, release]

env:
  JAVA_VERSION: '17'        # Java 17 是 2025 商店最低版本 :contentReference[oaicite:2]{index=2}
  ANDROID_COMPILE_SDK: '34' # targetSdk 34 满足 Play / OPPO 需求 :contentReference[oaicite:3]{index=3}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-${{ env.ANDROID_COMPILE_SDK }}
            build-tools;34.0.0            # 最新 Build-Tools :contentReference[oaicite:4]{index=4}

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - run: npm ci --prefer-offline --no-audit

      # 解码 JKS 到临时文件
      - name: Decode keystore
        run: |
          echo "$ANDROID_SIGNING_KEY_BASE64" | base64 -d > android/app/tsinghar-release.jks

      # 生成 release APK
      - name: Assemble
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon --stacktrace

      # 重命名并上传 Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apks
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 30
