name: Build (debug or release)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: debug / release
        required: true
        default: release
        type: choice
        options: [debug, release]

env:
  SDK_VERSION: '34'      # targetSdk / compileSdk
  JAVA_VERSION: '17'     # 必须 ≥17

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    # ① 拉取仓库
    - uses: actions/checkout@v4

    # ② 安装 JDK 17，并把 JAVA_HOME 写回环境
    - id: setup-java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: gradle
    - name: Export JAVA_HOME
      run: echo "JAVA_HOME=${{ steps.setup-java.outputs.path }}" >> $GITHUB_ENV

    # ③ 安装 Android SDK & 所需组件
    - uses: android-actions/setup-android@v3
      with:
        # 每行一个组件！一定要引号
        packages: |
          "platform-tools"
          "platforms;android-${{ env.SDK_VERSION }}"
          "build-tools;34.0.0"

    # ④ 安装 Node/依赖（如有用到 npm 或 react-native）
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - run: npm ci --prefer-offline --no-audit

    # ⑤ 写入 release 签名（keystore + gradle properties）
    - name: Prepare signing
      if: ${{ github.event.inputs.build_type == 'release' }}
      run: |
        echo "$ANDROID_SIGNING_KEY_BASE64" | base64 -d > android/app/tsinghar-release.jks
        cat <<EOF > android/keystore.properties
        storePassword=$ANDROID_KEYSTORE_PASSWORD
        keyPassword=$ANDROID_KEY_PASSWORD
        keyAlias=$ANDROID_KEY_ALIAS
        storeFile=tsinghar-release.jks
        EOF
      env:
        ANDROID_SIGNING_KEY_BASE64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
        ANDROID_KEYSTORE_PASSWORD:  ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_PASSWORD:       ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEY_ALIAS:          ${{ secrets.ANDROID_KEY_ALIAS }}

    # ⑥ 编译 APK
    - name: assemble${{ github.event.inputs.build_type }}
      run: |
        cd android
        ./gradlew assemble${{ github.event.inputs.build_type^ }} --no-daemon --stacktrace

    # ⑦ 通过 apksigner 验证 V2/V3 签名
    - name: Verify signing
      if: ${{ github.event.inputs.build_type == 'release' }}
      run: apksigner verify -v android/app/build/outputs/apk/release/*.apk

    # ⑧ 上传产物
    - uses: actions/upload-artifact@v4
      with:
        name: android-${{ github.event.inputs.build_type }}-apks
        path: android/app/build/outputs/apk/${{ github.event.inputs.build_type }}/*.apk
        retention-days: ${{ github.event.inputs.build_type == 'release' && 30 || 7 }}
