name: Build (debug / release)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: Select build type
        required: true
        default: debug
        type: choice
        options: [debug, release]

env:
  SDK_VERSION: "34"     # compileSdk/targetSdk
  JAVA_VERSION: "17"    # 必须 ≥17

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    # ① checkout
    - uses: actions/checkout@v4

    # ② JDK 17
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: gradle

    # ③ Android SDK（单行 + 自动接受许可）
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: "platform-tools platforms;android-${{ env.SDK_VERSION }} build-tools;34.0.0"
        accept-android-sdk-licenses: "true"   # ←关键:contentReference[oaicite:3]{index=3}

    # ④ Node & 依赖（如有 RN）
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: npm
    - run: npm ci --prefer-offline --no-audit

    # ⑤ 仅 release 时注入签名
    - name: Prepare signing
      if: ${{ inputs.build_type == 'release' }}
      run: |
        echo "${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}" | base64 -d > android/app/tsinghar-release.jks
        cat > android/keystore.properties <<EOF
        storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
        keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
        storeFile=tsinghar-release.jks
        EOF

    # ⑥ Build
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        if [[ "${{ inputs.build_type }}" == "release" ]]; then
          ./gradlew assembleRelease --no-daemon --stacktrace
        else
          ./gradlew assembleDebug   --no-daemon --stacktrace
        fi

    # ⑦ verify (release only)
    - name: Verify signing
      if: ${{ inputs.build_type == 'release' }}
      run: apksigner verify -v android/app/build/outputs/apk/release/*.apk

    # ⑧ upload artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-${{ inputs.build_type }}-apks
        path: |
          android/app/build/outputs/apk/${{ inputs.build_type }}/*.apk
        retention-days: 14   # 固定数字，表达式不支持 :contentReference[oaicite:4]{index=4}
